# Generated by Django 5.2.8 on 2025-11-23 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ДЕТИ', 'Дети'), ('ЖИВОТНЫЕ', 'Животные'), ('БОЛЬНЫЕ', 'Больные')], default='ДЕТИ', max_length=10, verbose_name='Категория получателя')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма пожертвования')),
                ('operation_index', models.CharField(max_length=50, unique=True, verbose_name='Индекс операции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
            ],
            options={
                'verbose_name': 'Запись о пожертвовании',
                'verbose_name_plural': 'Записи о пожертвованиях',
            },
        ),
    ]
